server:
  port: 9900

spring:
  datasource:
    url: jdbc:mysql://112.111.242.49:13020/db_test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: db_test
    password: tWyiEEMG3RJiKZ7j
    driver-class-name: com.mysql.cj.jdbc.Driver