server:
  port: 8101
  servlet:
    session:
      cookie:
        domain: localhost
        http-only: false
spring:
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB